# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QKontrola
                                 A QGIS plugin
 QKontrola
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-24
        copyright            : (C) 2026 by SpatialMind
        email                : info@spatialmind.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load QKontrola class from file qkontrola.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qkontrola import QKontrola

    return QKontrola(iface)
